// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828131214_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Models.CompletedCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("CompletedCourses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseCode = "MATH101",
                            CreditHours = 0,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseCode = "CS202",
                            CreditHours = 0,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseCode = "MATH101",
                            CreditHours = 0,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 4,
                            CourseCode = "CS202",
                            CreditHours = 0,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 5,
                            CourseCode = "MATH101",
                            CreditHours = 0,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 6,
                            CourseCode = "CS202",
                            CreditHours = 0,
                            StudentId = 4
                        });
                });

            modelBuilder.Entity("Shared.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MajorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SE101",
                            CreditHours = 3,
                            FacultyId = 1,
                            MajorId = 1,
                            Title = "Software Architecture"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CS202",
                            CreditHours = 4,
                            FacultyId = 1,
                            MajorId = 1,
                            Title = "Data Structures & Algorithms"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DB301",
                            CreditHours = 3,
                            FacultyId = 1,
                            MajorId = 1,
                            Title = "Database Systems"
                        },
                        new
                        {
                            Id = 4,
                            Code = "MATH101",
                            CreditHours = 3,
                            FacultyId = 1,
                            MajorId = 1,
                            Title = "Calculus 1"
                        },
                        new
                        {
                            Id = 5,
                            Code = "MATH102",
                            CreditHours = 3,
                            FacultyId = 1,
                            MajorId = 1,
                            Title = "Calculus 2"
                        });
                });

            modelBuilder.Entity("Shared.Models.CoursePrerequisite", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("PrerequisiteCourseId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "PrerequisiteCourseId");

                    b.HasIndex("PrerequisiteCourseId");

                    b.ToTable("CoursePrerequisite");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            PrerequisiteCourseId = 2
                        },
                        new
                        {
                            CourseId = 5,
                            PrerequisiteCourseId = 4
                        });
                });

            modelBuilder.Entity("Shared.Models.CourseSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("LecturerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("TaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Day = 1,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            LecturerName = "",
                            SectionName = "Section 1",
                            StartTime = new TimeSpan(0, 8, 30, 0, 0),
                            TaName = ""
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            Day = 2,
                            EndTime = new TimeSpan(0, 14, 30, 0, 0),
                            LecturerName = "",
                            SectionName = "Section 1",
                            StartTime = new TimeSpan(0, 12, 30, 0, 0),
                            TaName = ""
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            Day = 3,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            LecturerName = "",
                            SectionName = "Section 1",
                            StartTime = new TimeSpan(0, 10, 30, 0, 0),
                            TaName = ""
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 4,
                            Day = 0,
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            LecturerName = "",
                            SectionName = "Section 1",
                            StartTime = new TimeSpan(0, 8, 30, 0, 0),
                            TaName = ""
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 5,
                            Day = 2,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            LecturerName = "",
                            SectionName = "Section 1",
                            StartTime = new TimeSpan(0, 10, 30, 0, 0),
                            TaName = ""
                        });
                });

            modelBuilder.Entity("Shared.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colleges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Faculty of Engineering & Technology"
                        });
                });

            modelBuilder.Entity("Shared.Models.Major", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRegistrationOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Majors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollegeId = 1,
                            IsRegistrationOpen = false,
                            Name = "Computer Science"
                        });
                });

            modelBuilder.Entity("Shared.Models.MajorDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("MajorDto");
                });

            modelBuilder.Entity("Shared.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MajorId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("MajorId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacultyId = 1,
                            FullName = "Alex Morgan",
                            MajorId = 1,
                            Password = "849201",
                            RegistrationNumber = "210001",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            FacultyId = 1,
                            FullName = "Jordan Lee",
                            MajorId = 1,
                            Password = "371940",
                            RegistrationNumber = "210002",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            FacultyId = 1,
                            FullName = "Taylor Smith",
                            MajorId = 1,
                            Password = "592018",
                            RegistrationNumber = "210003",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            FacultyId = 1,
                            FullName = "Sam Wilson",
                            MajorId = 1,
                            Password = "148302",
                            RegistrationNumber = "210004",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Shared.Models.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourses");
                });

            modelBuilder.Entity("Shared.Models.StudentRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleSlotId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentRegistrations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseCode = "CS202",
                            CreditHours = 3,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 2,
                            CourseCode = "DB301",
                            CreditHours = 3,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseCode = "SE101",
                            CreditHours = 3,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 4,
                            CourseCode = "ENG101",
                            CreditHours = 3,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 5,
                            CourseCode = "",
                            CreditHours = 0,
                            ScheduleSlotId = 1,
                            StudentId = 4
                        });
                });

            modelBuilder.Entity("Shared.Models.CompletedCourse", b =>
                {
                    b.HasOne("Shared.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Shared.Models.Course", b =>
                {
                    b.HasOne("Shared.Models.Major", null)
                        .WithMany("TranscriptCourses")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.CoursePrerequisite", b =>
                {
                    b.HasOne("Shared.Models.Course", "Course")
                        .WithMany("Prerequisites")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Shared.Models.Course", "PrerequisiteCourse")
                        .WithMany()
                        .HasForeignKey("PrerequisiteCourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("PrerequisiteCourse");
                });

            modelBuilder.Entity("Shared.Models.CourseSchedule", b =>
                {
                    b.HasOne("Shared.Models.Course", "Course")
                        .WithMany("Schedules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Shared.Models.MajorDto", b =>
                {
                    b.HasOne("Shared.Models.Faculty", null)
                        .WithMany("Majors")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.Student", b =>
                {
                    b.HasOne("Shared.Models.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Shared.Models.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Faculty");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("Shared.Models.StudentCourse", b =>
                {
                    b.HasOne("Shared.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Shared.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Shared.Models.StudentRegistration", b =>
                {
                    b.HasOne("Shared.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Shared.Models.Course", b =>
                {
                    b.Navigation("Prerequisites");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Shared.Models.Faculty", b =>
                {
                    b.Navigation("Majors");
                });

            modelBuilder.Entity("Shared.Models.Major", b =>
                {
                    b.Navigation("TranscriptCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
